title: Hylla
description: A demo app that illustrates adaptive layout for foldables, based on borrowing devices from a QA fleet.
theme: jekyll-theme-primer
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
exclude:
  - assets/shelf-tags
